### ISSUE TITLE
error: target not found

### ISSUE THREAD

**Issue by nabeelalihashmi** [PhyTech-R0/dwm-phyOS#1]
phyOS-repo is up to date
error: target not found: phyOS-dwm
error: target not found: phyOS-dunst
error: target not found: phyOS-dwmblocks
error: target not found: phyOS-st
error: target not found: phyOS-fonts
error: target not found: phyOS-dmenu
error: target not found: phyOS-xmenu
error: target not found: lf

**Comment by r0-zero** [comment]
Database is online and running. Can you try again? Also it is only available in pacman.
