### ISSUE TITLE
how is the transparency achieved?

### ISSUE THREAD

**Issue by sewnie** [PhyTech-R0/dwm-phyOS#11]
i have been trying to do exactly this and all i'm getting is [uncleared bar text](https://www.reddit.com/r/suckless/comments/vxyv84/how_to_clear_drawbar_function_before_drawing/)

**Comment by r0-zero** [comment]
Hi, no transparency actually :p Bar has 3 seperate Xwindow

**Comment by sewnie** [comment]
> Hi, no transparency actually :p Bar has 3 seperate Xwindow

yes. how is that achieved then??
