### ISSUE TITLE
which picom fork are u using

### ISSUE THREAD

**Issue by Aneeqasif** [PhyTech-R0/dwm-phyOS#13]
i loved ur config but for the time being i can not re install my system unfortunately to try phy os, can u please tell how can i get your Alt+tab and the picom that u are using?

**Comment by ardishko** [comment]
It's picom-animations-git. as for the Alt+Tab, I don't know. 

https://aur.archlinux.org/packages/picom-animations-git

**Comment by r0-zero** [comment]
dcsillag fork of picom. As for rofi, checkout phyOS-system-scripts repo

**Comment by Aneeqasif** [comment]
> dcsillag fork of picom. As for rofi, checkout phyOS-system-scripts repo

yes i have cheked that rofi script but i is not showing icons i have chaged inifinity icons to my icon set , also i have copied ur rofi config.rasi but not change what should i do?

**Comment by r0-zero** [comment]
Put rofi scripts to your path (pOS-windowswitch) and config/rofi to your ~/.config/rofi

**Comment by Aneeqasif** [comment]
> Put rofi scripts to your path (pOS-windowswitch) and config/rofi to your ~/.config/rofi

yes i did it even then it was not working issue was in box.rasi the icon elements had 100 size which was causeing issue i tweaked it to human size icon i-e 46 and everything works fine.

**Comment by Aneeqasif** [comment]
one more thing that i want to point out  i was trying your picom conifg with fork that u mentioned there are boxy artifacts around rounded borders of blurred window above light backgrounds, is there any way around to avoid that , i have tried jhonaburgs fork in which these does not occur

![2022-07-27_23-32](https://user-images.githubusercontent.com/78728701/181346957-30306677-92ee-4931-87e1-5c2e48868a9f.png)
