### ISSUE TITLE
phyOS repo is unavailable.

### ISSUE THREAD

**Issue by ardishko** [PhyTech-R0/dwm-phyOS#14]
https://ft-labs.github.io/$repo/$arch just does not work.

If I try to do: sudo pacman -Syy phyOS-keyring, It does not work.
```

╰─$ sudo pacman -Syy phyOS-keyring
:: Synchronizing package databases...
 core                                                           157.0 KiB   518 KiB/s 00:00 [#####################################################] 100%
 extra                                                         1715.3 KiB  4.30 MiB/s 00:00 [#####################################################] 100%
 community                                                        6.7 MiB  9.04 MiB/s 00:01 [#####################################################] 100%
 multilib                                                       170.8 KiB  1761 KiB/s 00:00 [#####################################################] 100%
 phyOS-repo                                                      15.1 KiB   119 KiB/s 00:00 [#####################################################] 100%
resolving dependencies...
looking for conflicting packages...

Packages (1) phyOS-keyring-20240603-3

Total Download Size:   0.02 MiB
Total Installed Size:  0.00 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 phyOS-keyring-20240603-3-any                                    19.1 KiB   415 KiB/s 00:00 [#####################################################] 100%
(1/1) checking keys in keyring                                                              [#####################################################] 100%
(1/1) checking package integrity                                                            [#####################################################] 100%
error: phyOS-keyring: signature from "Arda Atci (arda@ftlabs.tech) <phystecharda@gmail.com>" is unknown trust
:: File /var/cache/pacman/pkg/phyOS-keyring-20240603-3-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] 
error: failed to commit transaction (invalid or corrupted package (PGP signature))
Errors occurred, no packages were upgraded.

```
as a solution, I suggest uploading the packages to the official arch repo. I need the components, not the entire package (as provided by the compiling option via git)

**Comment by r0-zero** [comment]
Hey, you need to sign if you are not using the iso. Here is the snippet:
```
    sudo pacman-key --recv-key 964FD85861C858D7 && sudo pacman-key --lsign-key $_
    sudo pacman -Syy phyOS-keyring
    sudo pacman-key --init
    sudo pacman-key --populate phyOS
```

**Comment by lumikalt** [comment]
❯ sudo pacman-key --recv-key 964FD85861C858D7 && sudo pacman-key --lsign-key $_
      sudo pacman -Syy phyOS-keyring
      sudo pacman-key --init
      sudo pacman-key --populate phyOS
gpg: key 964FD85861C858D7: "Arda Atci (arda@ftlabs.tech) <phystecharda@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
  -> Locally signed 1 keys.
==> Updating trust database...
gpg: next trustdb check due at 2022-08-09
:: Synchronizing package databases...
 testing                                             34.2 KiB  72.7 KiB/s 00:00 [---------------------------------------------] 100%
 core                                               157.0 KiB   316 KiB/s 00:00 [---------------------------------------------] 100%
 extra                                             1714.9 KiB  1703 KiB/s 00:01 [---------------------------------------------] 100%
 community-testing                                   18.8 KiB  40.8 KiB/s 00:00 [---------------------------------------------] 100%
 community                                            6.7 MiB  3.78 MiB/s 00:02 [---------------------------------------------] 100%
 multilib                                           170.9 KiB   657 KiB/s 00:00 [---------------------------------------------] 100%
 endeavouros                                         33.5 KiB  34.8 KiB/s 00:01 [---------------------------------------------] 100%
 chaotic-aur                                       1975.2 KiB  1869 KiB/s 00:01 [---------------------------------------------] 100%
 phyOS-repo                                          15.1 KiB  86.8 KiB/s 00:00 [---------------------------------------------] 100%
resolving dependencies...
looking for conflicting packages...

Package (1)               New Version  Net Change  Download Size

phyOS-repo/phyOS-keyring  20240603-3     0.00 MiB       0.02 MiB

Total Download Size:   0.02 MiB
Total Installed Size:  0.00 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 phyOS-keyring-20240603-3-any                        19.1 KiB  1123 KiB/s 00:00 [---------------------------------------------] 100%
(1/1) checking keys in keyring                                                  [---------------------------------------------] 100%
(1/1) checking package integrity                                                [---------------------------------------------] 100%
error: phyOS-keyring: signature from "Arda Atci (arda@ftlabs.tech) <phystecharda@gmail.com>" is unknown trust
:: File /var/cache/pacman/pkg/phyOS-keyring-20240603-3-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] 
error: failed to commit transaction (invalid or corrupted package (PGP signature))
Errors occurred, no packages were upgraded.
==> ERROR: The keyring file /usr/share/pacman/keyrings/phyOS.gpg does not exist.
This is the result of that...

**Comment by ardishko** [comment]
> This is the result of that...

yep.

**Comment by r0-zero** [comment]
Can you copy paste [phyOS-repo] section from your /etc/pacman.conf?

**Comment by r0-zero** [comment]
Can you try this:
sudo rm -r /etc/pacman.d/gnupg
sudo pacman-key --init
sudo pacman-key --populate archlinux
sudo pacman-key --recv-key 964FD85861C858D7 && sudo pacman-key --lsign-key $_
sudo pacman -Syy phyOS-keyring
sudo pacman-key --populate phyOS

**Comment by ardishko** [comment]
> Can you try this:
> sudo rm -r /etc/pacman.d/gnupg
> sudo pacman-key --init
> sudo pacman-key --populate archlinux
> sudo pacman-key --recv-key 964FD85861C858D7 && sudo pacman-key --lsign-key $_
> sudo pacman -Syy phyOS-keyring
> sudo pacman-key --populate phyOS

```
╰─$ sudo pacman -Syy phyOS-keyring
:: Synchronizing package databases...
 core                                                157.8 KiB   526 KiB/s 00:00 [##############################################] 100%
 extra                                              1714.5 KiB  6.34 MiB/s 00:00 [##############################################] 100%
 community                                             6.7 MiB  5.28 MiB/s 00:01 [##############################################] 100%
 multilib                                            170.9 KiB  1389 KiB/s 00:00 [##############################################] 100%
 phyOS-repo                                           15.1 KiB   122 KiB/s 00:00 [##############################################] 100%
resolving dependencies...
looking for conflicting packages...

Packages (1) phyOS-keyring-20240603-3

Total Download Size:   0.02 MiB
Total Installed Size:  0.00 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 phyOS-keyring-20240603-3-any                         19.1 KiB   112 KiB/s 00:00 [##############################################] 100%
(1/1) checking keys in keyring                                                   [##############################################] 100%
(1/1) checking package integrity                                                 [##############################################] 100%
error: phyOS-keyring: signature from "Arda Atci (arda@ftlabs.tech) <phystecharda@gmail.com>" is unknown trust
:: File /var/cache/pacman/pkg/phyOS-keyring-20240603-3-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: failed to commit transaction (invalid or corrupted package (PGP signature))
Errors occurred, no packages were upgraded.
╭─gorogorochan@Kamurocho /home/gorogorochan  ‹system› 
╰─$ sudo pacman-key --populate phyOS                                                                                               ↵ 1
==> ERROR: The keyring file /usr/share/pacman/keyrings/phyOS.gpg does not exist.

```
This is what the result is.

**Comment by r0-zero** [comment]
Is your signing key working correctly? It seems that you receive the key but signind does not work

**Comment by r0-zero** [comment]
Also can you copy paste /etc/pacman.conf

**Comment by lumikalt** [comment]
> Can you copy paste [phyOS-repo] section from your /etc/pacman.conf?

It's as you provided in the `README.md`, let me try the new command.

**Comment by lumikalt** [comment]
Yep, same error:
`error: phyOS-keyring: signature from "Arda Atci (arda@ftlabs.tech) <phystecharda@gmail.com>" is unknown trust
:: File /var/cache/pacman/pkg/phyOS-keyring-20240603-3-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] 
error: failed to commit transaction (invalid or corrupted package (PGP signature))
Errors occurred, no packages were upgraded.
==> ERROR: The keyring file /usr/share/pacman/keyrings/phyOS.gpg does not exist.`

**Comment by lumikalt** [comment]
For reference,
/etc/pacman.conf has:

`[phyOS-repo]`
`  SigLevel = Required DatabaseOptional`
`  Server = https://FT-Labs.github.io/$repo/$arch`

**Comment by r0-zero** [comment]
What is the output of:
sudo pacman-key --lsign-key 964FD85861C858D7

**Comment by ardishko** [comment]
```
╰─$ sudo pacman-key --lsign-key 964FD85861C858D7
[sudo] password for gorogorochan: 
  -> Locally signed 1 keys.
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   8  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   8  signed:  93  trust: 2-, 0q, 0n, 6m, 0f, 0u
gpg: depth: 2  valid:  70  signed:  30  trust: 70-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2022-08-09
```

that's the output.

**Comment by ardishko** [comment]
Why all the need for troubleshooting though? Can't you just submit these to the official arch repository? It would save lots of us Arch users a lot of trouble.

**Comment by lumikalt** [comment]
Oh... huh. The problem was with $_ (on the sign-key command) not expanding correctly on my system? How very odd. If I manually insert the key code the command works. Sorry for not trying it sooner!

**Comment by lumikalt** [comment]
I expect it to be a shell error, as some don't use $_ in that way (I use fish, and the command is for zsh, which should work the same for bash). Alas, use this:

sudo pacman-key --recv-key 964FD85861C858D7 && sudo pacman-key --lsign-key 964FD85861C858D7
sudo pacman -Syy phyOS-keyring
pacman-key --init
pacman-key --populate phyOS

**Comment by r0-zero** [comment]
Sorry guys that is my bad then. I will upload to AUR when i have time, it felt weird because I tested this on 4 different computers

**Comment by ardishko** [comment]
Sorun yok en azından soruna çözüm bulduk :+1:

**Comment by r0-zero** [comment]
@ardishco-the-great Bir turkun ilgisini cekmesi beni mutlu etti :D

**Comment by ardishko** [comment]
@FT-Labs hem türk hem de adaşın olan birinin ilgisini çektin :)

**Comment by r0-zero** [comment]
@ardishco-the-great Sevindim discord kanalina beklerim adas :)

**Comment by ardishko** [comment]
Kanalın linkini profilinde, disboard, betterdiscord serverlistte aradım ama bulamadım, linkini nerede bulabilirim?

**Comment by r0-zero** [comment]
https://discord.gg/UHdZ4Pzve3
