### ISSUE TITLE
Cant install phyOS-dwm

### ISSUE THREAD

**Issue by zeroruka** [PhyTech-R0/dwm-phyOS#15]
Hi, I am using endeavouros with gnome desktop right now, and have been trying to install phyOS-dwm. However, when I tried to start dwm from the login screen, it just returns me back to login. I have setup everything according to this repo. dotfiles have also been put into my home directory. I have tried disabling wayland on gnome but it didn't change anything as well. Im not sure if it's path issue, since I didn't know what to set in path.

**Comment by r0-zero** [comment]
Hello! Readme is outdated in phyOS-dwm, can you install all packages prefixed with phyOS (dont install themes) in phyOS-iso/packages.x86_64

**Comment by zeroruka** [comment]
Thanks! That worked.
