### ISSUE TITLE
Picom blurring issues on older hardware

### ISSUE THREAD

**Issue by arch-user-france1** [PhyTech-R0/dwm-phyOS#18]
Please fix the following bug:

Wow GitHub buggy too doesn't let me uploads let's try again ah doesn't work

Basically if I open more than two windows it starts glitching and flackering around which is very bad for health.

Using some old apple laptop. Resolution is terrible since yay -Syu too, WLAN driver is not the right one, it's the one that has terrible performance and phyup dots --force does not work - it doesn't create the hard link.

**Comment by r0-zero** [comment]
It should not make a hard link, that's working correctly. As for resolution, you can try Win+F5 for setting resolution yourself (try toggling dynamic resolution on/off). As for the other one with glitches, it happened on some old computers too. It is a picom issue, I am trying to handle it. Maybe it is because of old drivers.

**Comment by arch-user-france1** [comment]
Thank you for this quick response <3

It first worked then I rebooted and then this issue happened I think. Not sure though.

How long will it take to handle this issue?
I would like to being able using my laptop tomorrow.

**Comment by r0-zero** [comment]
Can you come to discord? Im helping who have issues from there, can help you too (click discord button in phyOS-iso repo)

**Comment by arch-user-france1** [comment]
Okay sure. Discord is an enemy of mine but I'll do it.

> Can you come to discord? Im helping who have issues from there, can help you too (click discord button in phyOS-iso repo)

**Comment by arch-user-france1** [comment]
I have joined the discord but I don't know what to do now
And why is --experimental-backends given to picom? Might that make a difference?

**Comment by r0-zero** [comment]
Anyone having this issue, remove --experimental-backends option from $HOME/.xprofile

**Comment by arch-user-france1** [comment]
It turned out that blurring is the problem and not experimental backens. Kernel blurring doesn't need experimental backens and still has the same problem.

**Comment by arch-user-france1** [comment]
https://github.com/yshui/picom/issues/871

Issue is reported there
