### ISSUE TITLE
Patch request for split bar

### ISSUE THREAD

**Issue by namishh** [PhyTech-R0/dwm-phyOS#22]
or at least tell me the code changes required

**Comment by r0-zero** [comment]
Hi,

I really don't have time currently, but Im adding the commits here.

1:  https://github.com/FT-Labs/pdwm/commit/cf4b105da2110da00027ab539a1061d85b5f4b82

2:  https://github.com/FT-Labs/pdwm/commit/f32f4c190e3268fb02a753b8b852342cc3cba639

3: https://github.com/FT-Labs/pdwm/commit/a4ae621ec4e6da62f21e4c295748b9b68a83864c

4: https://github.com/FT-Labs/pdwm/commit/eb3b73ec8a2fc97307dd4063f4afab42a5e7afb7

Sorry, its a bit of mess :(

**Comment by namishh** [comment]
No worries mate!
But kindly do tell what each of the commits achieve

**Comment by r0-zero** [comment]
At first, I thought it makes more sense for each monitor to have 3 bars. 1-2 is actually those, but after that I noticed that most of the base dwm functions doesn't work that way. They only update statusbar on the selected monitor, then I thought that it was reduntant, and uses unnecessary memory.
3-4 fixes that each monitor will have only and only one bar, which is the left one with tags. Middle bar and rightmost bar are shared between monitor, they will move to whichever is focused
