### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by josephgerth** [PhyTech-R0/dwm-phyOS#24]
Good morning,

I was able to get through all of the installation process until the very end. I have my pacman set up and updated. Then the readme tells me to `pacman -Syy` 
and then 
`curl [https://raw.githubusercontent.com/FT-Labs/phyOS-Aug-22/master/packages.x86_64](https://raw.githubusercontent.com/FT-Labs/phyOS-Aug-22/master/packages.x86_64) | sed -e '/\#/d' | tr -s "\n" | xargs sudo pacman -S --noconfirm`

The former works just fine. But the latter returns `zsh: unknown file attribute: h error: no targets specified (use -h for help`

I literally copied and pasted that second curl code into my terminal, so I assume it's correct. But there are several commands I am not familiar with, so I'm posting this here for some guidance.

Thank you.

**Comment by r0-zero** [comment]
In the curl command delete the markup only the link should be there, i wrote it wron mb

**Comment by josephgerth** [comment]
This time I typed in `curl https://raw.githubusercontent.com/FT-Labs/phyOS-Aug-22/master/packages.x86_64 https://raw.githubusercontent.com/FT-Labs/phyOS-Aug-22/master/packages.x86_64 | sed -e '/\#/d' | tr -s "\n" | xargs sudo pacman -S --noconfirm`

and I got several warnings; most of these programs I already have so it the warning essentially told me that it was reinstalling.

Some of the programs gave me a "target not found".

I'm wondering if this is correct, or if I've done something else incorrectly.

I'm pretty sure I've done everything else correctly---I did change my pacman.conf and added phyos-repo. I did pacman -Syy.

**Comment by r0-zero** [comment]
curl https://raw.githubusercontent.com/FT-Labs/phyOS-Aug-22/master/packages.x86_64 | sed -e '/\#/d' | tr -s "\n" | xargs sudo pacman -S --noconfirm

Could you try this please?

**Comment by josephgerth** [comment]
Same issue:

`$ curl https://raw.githubusercontent.com/FT-Labs/phyOS-Aug-22/master/packages.x86_64 | sed -e '/#/d' | tr -s "\n" | xargs sudo pacman -S --noconfirm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2923  100  2923    0     0  16930      0 --:--:-- --:--:-- --:--:-- 16994
[sudo] password for desktop: 
warning: arandr-0.1.11-1 is up to date -- reinstalling
warning: base-3-1 is up to date -- reinstalling
warning: btrfs-progs-6.1.3-1 is up to date -- reinstalling
warning: curl-7.87.0-3 is up to date -- reinstalling
.
.
.
error: target not found: i3lock-color
error: target not found: betterlockscreen
.
.
.
warning: unclutter-1:1.6-2 is up to date -- reinstalling`

**Comment by r0-zero** [comment]
it states everything is installed

**Comment by josephgerth** [comment]
Yes; but your explanation points out that after a reboot I'll be running on this window manager. This is not the case; I'm still on my old window manager.

I have a config file that opens dwm on login (after login, I then type in `startx` on tty), so maybe I need to call a different wm? Or maybe the config files didn't download? Or maybe I failed to follow directions elsewhere?

**Comment by r0-zero** [comment]
Are you using a display manager? There should be a pdwm option there. Also you can get the dotfiles by:
phyup dots --force
