### ISSUE TITLE
error occurred renewing keyring

### ISSUE THREAD

**Issue by digger-yu** [PhyTech-R0/dwm-phyOS#28]
error occurred renewing keyring when select "REFRESH PACMAN MIRRORS"

![86d6213e-0748-44f1-935b-7641f8237e9f](https://github.com/FT-Labs/pdwm/assets/55081697/7a75f681-ef89-4718-a2bd-ce8a95bc2c76)

**Comment by r0-zero** [comment]
Old iso is old, please continue with offline installer. Also online installer will be removed in the next release as well, please download anything you want after the installation
