### ISSUE TITLE
gpg: error reading key: No public key

### ISSUE THREAD

**Issue by ProfiGMan** [PhyTech-R0/dwm-phyOS#30]
Hi! Doing just as described in README:

> sudo pacman-key --recv-key 964FD85861C858D7
> sudo pacman-key --lsign-key 964FD85861C858D7
> sudo pacman -Syy phyOS-keyring
> sudo pacman-key --init
> sudo pacman-key --populate phyOS

But the last command gives this error:

> ==> Appending keys from phyOS.gpg...
> gpg: error reading key: No public key
> ==> Locally signing trusted keys in keyring...
> ==> ERROR: 5E29997979B066C7CCF502FE7B2148AD90FEEC50 could not be locally signed.

Im using Arch

**Comment by r0-zero** [comment]
Could you try again? It should be fixed now.
