### ISSUE TITLE
Command not found: phyup

### ISSUE THREAD

**Issue by Kurburis** [PhyTech-R0/dwm-phyOS#32]
Greetings, 

I am trying to install this on arch linux. I've installed the necessary packages and built both pdwm and pdwmc. When I try to run the `phyup dots --force' command, it cannot be found. Do you know what could be the problem?

**Comment by dnchshrp** [comment]
I have the same issue

**Comment by r0-zero** [comment]
Could you install ``` phyOS-system-scripts ```, it is included in this package
