### ISSUE TITLE
just wanted to say thanks 

### ISSUE THREAD

**Issue by sewnie** [PhyTech-R0/dwm-phyOS#4]
thank you for your work and this project ❤️

**Comment by sewnie** [comment]
on a seperate note: please upstream your patches to the suckless wiki, they are very useful.

**Comment by r0-zero** [comment]
Thanks for your comment! I have mailed them, but they still did not put it on the site. I think they will put it soon!

**Comment by sewnie** [comment]
> Thanks for your comment! I have mailed them, but they still did not put it on the site. I think they will put it soon!

i don't think thats how this works.

https://suckless.org/wiki/
see this.
i uploaded a patch and it got accepted in a few days via this method.

**Comment by r0-zero** [comment]
Oh, I just mailed it through wiki, my bad for misreading. Thanks again!

**Comment by sewnie** [comment]
no,, i meant you read the link i gave you. https://suckless.org/wiki/

you add your patches by committing to the sites/ repository.
