### ISSUE TITLE
proper sticky

### ISSUE THREAD

**Issue by explosion-mental** [PhyTech-R0/dwm-phyOS#5]
hello phy
saw ur commit about not focusing sticky windows,
might wanna check out this pr https://github.com/LukeSmithxyz/dwm/pull/181, think it 'fixes' this behaviour pretty well

the `ISVISIBLE(c) || c->issticky` thing makes impossible to focus sticky windows if they are alone in a tag with `focusstack()` keybinding (you can still focus the window with the mouse).

**Comment by r0-zero** [comment]
Thanks, merged it!
